/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\Mountain.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/Mountain.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Landscape005.geometry}
        material={materials['Material.003']}
        rotation={[Math.PI, 0, Math.PI]} 
        castShadow
        receiveShadow
      >
        <meshStandardMaterial attach="material" color="green" />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/Mountain.glb')
